jobs:
  test: 
    runs-on: ubuntu-18.04 
    steps: 
      -
        name: checkout
        uses: actions/checkout@v2
      -
        name: check-resources
        run: free -h; df -h; lscpu;
      -
        name: build-context
        run: mkdir build/
      -
        name: build-hasher
        run: docker build -f hasher/Dockerfile -t fav1c0n/ruby:sinatra-thin hasher/
      -
        name: build-rng
        run: docker build -f rng/Dockerfile -t eleigle/python:Flask build/
      -
        name: build-webui
        run: docker build -f webui/Dockerfile -t eleigle/node:express-redis webui/
      -
        name: build-worker
        run: docker build -f worker/Dockerfile -t eleigle/python:Redis-requests build/
      -
        name: oc-install
        run: |
          wget https://downloads-openshift-console.apps.openshift.sebastian-colomar.es/amd64/linux/oc.tar
          tar xf oc.tar
          chmod +x oc
          rm -f oc.tar
          ./oc version
      -
        name: oc-login
        run: ./oc login --token=sha256~oYdFK2xGCdu03X0WpANaES7hTc6Tw8A89LkcYnD5-UA --server=https://api.openshift.sebastian-colomar.es:6443
      -
        name: deploy
        run: ./oc apply -f etc/kubernetes/manifests/
      -
        name: test-worker
        run: |
          while true
          do sleep 10
          ./oc logs dc/dc-worker 2>& 1 | grep Coin.found && break
          done
      -
        name: test-webui
        run: |
          while true
          do sleep 10
          ./oc logs svc/svc-webui 2>& 1 | grep WEBUI.running && break
          done
name: CI
on: 
  push: 
    branches: 
      - 
        2022-03-santander
